site_name: Cray-LM Docs
nav:
    - Getting Started:
        - Introduction: index.md
        - Quick Start: quickstart.md
        - Architecture: arch.md
        - Contact: contact.md
    - Examples:
        - Inference: inference.md
        - Training: training.md
    - Command Line:
        - CLI: cli/cli.md
        - List Models: cli/list-models.md
        - Training Logs: cli/training-logs.md
        - Squeue: cli/squeue.md
        - Plot: cli/plot.md
    - Deployment:
        - Laptop: deployment/laptop.md
        - Kubernetes: deployment/kubernetes.md
        - Modal: deployment/modal.md
