# Default values for cray-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: gdiamos/masint-arm
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000
  targetPort: 8000

volumes:
  - name: ml
    path: /app/cray/ml
    hostPath: /Users/gregorydiamos/checkout/cray/ml

network:
  name: cray-network

