model: masint/tiny-random-llama
api_url: https://greg1232--deployment-modal-examples-cray-cray-py-fas-f8ed38-dev.modal.run
vllm_api_url: https://greg1232--deployment-modal-examples-cray-cray-py-vllm-app-dev.modal.run
