image:
  repository: tensorwave/scalarlm-amd
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000
  targetPort: 8000
  externalIP: 104.171.203.79

model: meta-llama/Llama-3.2-3B-Instruct
max_model_length: 4096
gpu_memory_utilization: 0.33

training_gpus: 2
inference_gpus: 6

