name: Build AMD image using depot

on:
  workflow_dispatch:


jobs:
  docker-image:
    runs-on: depot-ubuntu-22.04-8
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Depot CLI
        uses: depot/setup-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: depot/build-push-action@v1
        env:
          DEPOT_TOKEN: ${{ secrets.DEPOT_TOKEN }}
        with:
          # if no depot.json file is at the root of your repo, you must specify the project id
          project: 39xfdrxfqt
          push: true
          tags: gdiamos/cray-amd:latest
          build-args: |
            BASE_NAME=amd
            VLLM_TARGET_DEVICE=rocm
            TORCH_CUDA_ARCH_LIST="gfx906 gfx908 gfx90a gfx940 gfx941 gfx942 gfx1030 gfx1100"
            MAX_JOBS=8



