permissions:
  # allow issuing OIDC tokens for this workflow run
  id-token: write
  # allow at least reading the repo contents, add other permissions if necessary
  contents: read
steps:
  # no need to provide a DEPOT_TOKEN
  - uses: depot/build-push-action@v1
